---

- name: install the latest version of nginx
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - nginx-full

- name: ensure nginx is always running
  service:
    name: nginx
    state: started
    enabled: yes
