---

- name: install the latest version of nginx
  package:
    name: nginx-full
    state: latest

- name: ensure nginx is always running
  service:
    name: nginx
    state: started
    enabled: yes
