---

- name: install the latest version of mongodb, python-pymongo
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - mongodb
    - python-pymongo

- name: ensure mongodb is always running
  service:
    name: mongodb
    state: started
    enabled: yes
