---

- name: install the latest version of uwsgi
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - uwsgi

- name: ensure uwsgi is always running
  service:
    name: uwsgi
    state: started
    enabled: yes
