---

- name: install the latest version of postgresql
  package:
    name: postgresql
    state: latest

- name: install the latest version of python-psycopg2
  package:
    name: python-psycopg2
    state: latest

- name: ensure postgresql is always running
  service:
    name: postgresql
    state: started
    enabled: yes
