---

- name: install the latest version of postgresql, python-psycopg2
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - postgresql
    - python-psycopg2

- name: ensure postgresql is always running
  service:
    name: postgresql
    state: started
    enabled: yes
