---

- name: install the latest version of python3, python3-dev, virtualenv, python3-pip
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3
    - python3-dev
    - virtualenv
    - python3-pip
