---

- name: Disable requiretty in sudoers (allows for pipelining and better performance, ansible secure execution)
  lineinfile:
    dest: /etc/sudoers
    line: 'Defaults requiretty'
    state: absent
  vars:
      ansible_ssh_pipelining: no

- name: install the latest version of vim, zsh, tmux, net-tools, git
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim
    - zsh
    - tmux
    - net-tools
    - git

- name: create nyx, jalopez users for administration, add to sudo group
  user:
    name: "{{ item.username }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    append: yes
  with_items:
    - username: nyx
      shell: /bin/zsh
      groups: sudo
    - username: jalopez
      shell: /bin/bash
      groups: sudo
